# Generated by Django 5.2.2 on 2025-06-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0004_genre_song_artwork_song_track_number_song_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='gpx_synced',
            field=models.BooleanField(default=False),
        ),
    ]
